### ISSUE TITLE
API의 요청방법에 따라 인코딩이 달라지는 문제

### ISSUE THREAD

**Issue by redtea89** [2nd-wanted-pre-onboarding-team-A/Human-Scape-Wanted-A#17]
postman이나 insomnia에서는 정상작동하지만 브라우저나 curl에서는 글자가 깨져서 나타나고 있습니다. 

이 부분의 해결방법이 있을지 고민해봐야 할 것 같아 이슈로 남겨놓습니다.

**Comment by tasddc1226** [comment]
## [배포 주소](http://wanted-ateam.xyz/api/v1/research)로 접속 시 브라우저 결과 화면
![Screen Shot 2022-05-12 at 14 48 28](https://user-images.githubusercontent.com/55699007/168000741-7b2f6f68-8156-45ef-a0b9-9dfb9bb715b8.png)

**Comment by fore0919** [comment]
[해결 방법](https://hashcode.co.kr/questions/11530/python-django-jsonresponse%EC%97%90%EC%84%9C-%ED%95%9C%EA%B8%80-%EC%9D%B8%EC%BD%94%EB%94%A9-%EB%AC%B8%EC%A0%9C-%EC%A7%88%EB%AC%B8%EC%9E%85%EB%8B%88%EB%8B%A4)
